trigger:
- master

pool:
  name: selfhostedagent
  demands:
    - agent.name -equals agent1

stages:
  - stage: CodeCompile
    displayName: 'Code Compile'
    jobs:
      - job:
        steps:
          - task: Maven@4
            inputs:
              azureSubscription: 'serviceconn'
              mavenPomFile: 'pom.xml'
              goals: 'compile'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
  - stage: codeTest
    displayName: 'Code Test'
    jobs:
      - job:
        steps:
          - task: Maven@4
            inputs:
              azureSubscription: 'serviceconn'
              mavenPomFile: 'pom.xml'
              goals: 'test'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
  - stage: trivyScan
    displayName: 'Trivy Scan'
    jobs:
      - job:
        steps:
          - task: CmdLine@2
            inputs:
              script: 'trivy fs --format table -o fs.html .'
  - stage: SonarqubeCode
    displayName: 'SonarQubeCodeAnalysis'
    jobs:
      - job:
        steps:
          - task: SonarQubePrepare@7
            inputs:
              SonarQube: 'sonarconn1'
              scannerMode: 'cli'
              configMode: 'manual'
              cliProjectKey: 'SecretsantaWeb'
              cliProjectName: 'SecretsantaWeb'
              cliSources: '.'
              extraProperties: 'sonar.java.binaries=.'
          - task: SonarQubeAnalyze@7
            inputs:
              jdkversion: 'JAVA_HOME_17_X64'
          - task: SonarQubePublish@7
            inputs:
              pollingTimeoutSec: '300'