apiVersion: apps/v1
kind: Deployment
metadata:
  name: santa-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: santa
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  progressDeadlineSeconds: 600  # Extended deadline for rollout to complete
  template:
    metadata:
      labels:
        app: santa
    spec:
      containers:
        - name: santa
          image: secretsantaweb.azurecr.io/dev:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8089
          readinessProbe:
            httpGet:
              path: /health
              port: 8089
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8089
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:  # Optional resource constraints
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"

---

apiVersion: v1
kind: Service
metadata:
  name: santa-ssvc
spec:
  selector:
    app: santa
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
  type: LoadBalancer
